"""Tests for ManifestGenerator."""

import shutil
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.manifest import ManifestGenerator
from core.storage import MemoryStore


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def temp_dir():
    tmp = tempfile.mkdtemp()
    yield Path(tmp)
    shutil.rmtree(tmp)


@pytest.fixture
def store(temp_dir):
    return MemoryStore(base_dir=str(temp_dir))


@pytest.fixture
def generator(store):
    return ManifestGenerator(store)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def add_memory(store, stage, filename, title, summary, importance=0.5, content=None):
    """Create a test memory and return its ID."""
    return store.create(
        filename,
        content or f'Content for {title}',
        {
            'stage': stage,
            'title': title,
            'summary': summary,
            'importance': importance,
        },
    )


# ---------------------------------------------------------------------------
# Empty-store tests
# ---------------------------------------------------------------------------


class TestManifestEmpty:
    def test_generate_empty_store(self, generator):
        """generate() returns valid markdown with no stage sections when store is empty."""
        result = generator.generate()
        assert result.startswith('# Memory')
        assert '<!-- Auto-generated by memesis plugin -->' in result
        # No stage headers when no memories
        assert '## Instinctive' not in result
        assert '## Crystallized' not in result
        assert '## Consolidated' not in result

    def test_token_budget_empty_store(self, generator):
        """estimate_token_budget() returns (0, 0.0) for empty store."""
        count, pct = generator.estimate_token_budget()
        assert count == 0
        assert pct == 0.0

    def test_write_manifest_creates_file(self, generator, store):
        """write_manifest() creates MEMORY.md in base_dir."""
        generator.write_manifest()
        manifest_path = store.base_dir / 'MEMORY.md'
        assert manifest_path.exists()
        content = manifest_path.read_text()
        assert '# Memory' in content

    def test_write_manifest_is_atomic(self, generator, store, monkeypatch):
        """write_manifest() uses tmp+rename — original file not corrupted on failure."""
        import shutil
        manifest_path = store.base_dir / 'MEMORY.md'

        # Write an initial valid manifest
        generator.write_manifest()
        original_content = manifest_path.read_text()
        assert '# Memory' in original_content

        # Patch shutil.move to fail mid-write
        def failing_move(src, dst):
            raise OSError("simulated disk full")
        monkeypatch.setattr(shutil, 'move', failing_move)

        # write_manifest() should raise but leave the original untouched
        with pytest.raises(OSError):
            generator.write_manifest()

        # Original file must be intact
        assert manifest_path.exists()
        assert manifest_path.read_text() == original_content


# ---------------------------------------------------------------------------
# Format / structure tests
# ---------------------------------------------------------------------------


class TestManifestFormat:
    def test_instinctive_section_present(self, store, generator):
        add_memory(store, 'instinctive', 'ruby_style.md', 'Ruby Style', 'Idiomatic Ruby tips')
        result = generator.generate()
        assert '## Instinctive (always loaded)' in result
        assert '[Ruby Style]' in result
        assert 'Idiomatic Ruby tips' in result

    def test_crystallized_section_with_importance(self, store, generator):
        add_memory(store, 'crystallized', 'payment.md', 'Payment Pipeline', 'Check lock ordering', importance=0.78)
        result = generator.generate()
        assert '## Crystallized (context-matched)' in result
        assert '[importance: 0.78]' in result

    def test_consolidated_section_present(self, store, generator):
        add_memory(store, 'consolidated', 'arch.md', 'Memory Architecture', 'Chose lifecycle approach')
        result = generator.generate()
        assert '## Consolidated (available via search)' in result
        assert '[Memory Architecture]' in result

    def test_ephemeral_excluded(self, store, generator):
        add_memory(store, 'ephemeral', 'scratch.md', 'Scratch Note', 'Ephemeral content')
        result = generator.generate()
        # Ephemeral must not appear as a stage header or as an entry
        assert '## Ephemeral' not in result
        assert '[Scratch Note]' not in result

    def test_metadata_comment_includes_total_and_budget(self, store, generator):
        add_memory(store, 'instinctive', 'r.md', 'Ruby', 'Ruby style')
        add_memory(store, 'crystallized', 'c.md', 'Crystal', 'Crystal hint', importance=0.6)
        result = generator.generate()
        assert 'Total: 2' in result
        assert 'Token budget:' in result

    def test_relative_path_in_link(self, store, generator):
        """Link paths must be relative to store.base_dir."""
        add_memory(store, 'instinctive', 'style.md', 'Style Guide', 'Style notes')
        result = generator.generate()
        # Absolute path must not appear in the link
        assert str(store.base_dir) not in result
        assert 'instinctive/style.md' in result

    def test_summary_truncated_to_150_chars(self, store, generator):
        long_summary = 'A' * 200
        add_memory(store, 'consolidated', 'long.md', 'Long Entry', long_summary)
        result = generator.generate()
        # The displayed summary must be <= 150 chars + ellipsis
        # Find the line and check the dash-separated part
        for line in result.splitlines():
            if '[Long Entry]' in line:
                after_dash = line.split('\u2014', 1)[-1].strip()
                assert len(after_dash) <= 151  # 150 + ellipsis char
                assert after_dash.endswith('\u2026')
                break
        else:
            pytest.fail('Long Entry line not found in manifest')


# ---------------------------------------------------------------------------
# Ordering tests
# ---------------------------------------------------------------------------


class TestManifestOrdering:
    def test_crystallized_sorted_by_importance_descending(self, store, generator):
        add_memory(store, 'crystallized', 'low.md', 'Low', 'Low importance', importance=0.3)
        add_memory(store, 'crystallized', 'high.md', 'High', 'High importance', importance=0.9)
        add_memory(store, 'crystallized', 'mid.md', 'Mid', 'Mid importance', importance=0.6)

        result = generator.generate()
        high_pos = result.index('[High]')
        mid_pos = result.index('[Mid]')
        low_pos = result.index('[Low]')
        assert high_pos < mid_pos < low_pos

    def test_consolidated_sorted_by_updated_at_descending(self, store, generator):
        """Consolidated memories appear newest-first (updated_at DESC)."""
        # Create in order; the last one has the latest updated_at.
        add_memory(store, 'consolidated', 'first.md', 'First', 'Created first')
        add_memory(store, 'consolidated', 'second.md', 'Second', 'Created second')
        add_memory(store, 'consolidated', 'third.md', 'Third', 'Created third')

        result = generator.generate()
        # Third was created last → most recent updated_at → appears first
        third_pos = result.index('[Third]')
        second_pos = result.index('[Second]')
        first_pos = result.index('[First]')
        assert third_pos < second_pos < first_pos

    def test_stage_section_order(self, store, generator):
        """Instinctive section appears before Crystallized, which appears before Consolidated."""
        add_memory(store, 'instinctive', 'i.md', 'Inst', 'instinctive memory')
        add_memory(store, 'crystallized', 'c.md', 'Crys', 'crystallized memory', importance=0.7)
        add_memory(store, 'consolidated', 'o.md', 'Cons', 'consolidated memory')

        result = generator.generate()
        inst_pos = result.index('## Instinctive')
        crys_pos = result.index('## Crystallized')
        cons_pos = result.index('## Consolidated')
        assert inst_pos < crys_pos < cons_pos


# ---------------------------------------------------------------------------
# Token budget tests
# ---------------------------------------------------------------------------


class TestTokenBudget:
    def test_budget_reflects_file_sizes(self, store, generator):
        """Token count is roughly char_count // 4."""
        content = 'X' * 800  # 800 chars → ~200 tokens
        store.create('style.md', content, {'stage': 'instinctive', 'title': 'Style', 'summary': ''})

        count, pct = generator.estimate_token_budget()
        # File also has frontmatter, so char count will be > 800
        # Just verify it's in the right ballpark (within 10%)
        file_path = store.base_dir / 'instinctive' / 'style.md'
        actual_chars = len(file_path.read_text())
        expected_tokens = actual_chars // 4
        assert abs(count - expected_tokens) <= expected_tokens * 0.10

    def test_budget_percentage_is_fraction_of_200k(self, store, generator):
        """Percentage is token_count / 200_000."""
        count, pct = generator.estimate_token_budget()
        if count > 0:
            assert abs(pct - count / 200_000) < 1e-9
        else:
            assert pct == 0.0

    def test_budget_top10_crystallized_only(self, store, generator):
        """Only top-10 crystallized memories by importance contribute to budget."""
        # Create 12 crystallized memories with known importance values
        for i in range(12):
            store.create(
                f'c{i}.md',
                'Z' * 400,
                {
                    'stage': 'crystallized',
                    'title': f'Crystal {i}',
                    'summary': '',
                    'importance': i / 12,
                },
            )

        # Estimate includes only top-10 by importance
        count, _ = generator.estimate_token_budget()
        assert count > 0
        # The two lowest importance entries should not inflate the count
        # (there's no way to assert the exact boundary without knowing frontmatter size,
        # but we can verify count is less than all-12 would produce)
        crystallized_all = store.list_by_stage('crystallized')
        total_chars_all = sum(
            len(Path(m['file_path']).read_text()) for m in crystallized_all
        )
        tokens_all = total_chars_all // 4
        assert count < tokens_all  # top-10 < all-12


# ---------------------------------------------------------------------------
# Idempotency test
# ---------------------------------------------------------------------------


class TestManifestIdempotency:
    def test_generate_is_idempotent(self, store, generator):
        """Same store state always produces the same manifest (minus timestamp)."""
        add_memory(store, 'instinctive', 'r.md', 'Ruby', 'Ruby style')
        add_memory(store, 'crystallized', 'c.md', 'Crystal', 'Crystal hint', importance=0.7)
        add_memory(store, 'consolidated', 'o.md', 'Cons', 'Consolidated note')

        result1 = generator.generate()
        result2 = generator.generate()

        # Strip the timestamp line before comparing
        def strip_timestamp(text):
            return '\n'.join(
                line for line in text.splitlines()
                if 'Last updated:' not in line
            )

        assert strip_timestamp(result1) == strip_timestamp(result2)

    def test_write_then_generate_stable(self, store, generator):
        """write_manifest() followed by generate() produces the same content."""
        add_memory(store, 'instinctive', 'r.md', 'Ruby', 'Ruby style')
        generator.write_manifest()

        manifest_path = store.base_dir / 'MEMORY.md'
        written = manifest_path.read_text()
        regenerated = generator.generate()

        def strip_timestamp(text):
            return '\n'.join(
                line for line in text.splitlines()
                if 'Last updated:' not in line
            )

        assert strip_timestamp(written) == strip_timestamp(regenerated)


# ---------------------------------------------------------------------------
# write_manifest path test
# ---------------------------------------------------------------------------


class TestWriteManifest:
    def test_writes_to_correct_location(self, store, generator):
        generator.write_manifest()
        expected = store.base_dir / 'MEMORY.md'
        assert expected.exists()

    def test_overwrites_existing_manifest(self, store, generator):
        """Calling write_manifest() twice overwrites the previous file."""
        add_memory(store, 'instinctive', 'r.md', 'Ruby', 'First summary')
        generator.write_manifest()

        first_content = (store.base_dir / 'MEMORY.md').read_text()

        # Update the memory title so the manifest differs
        memories = store.list_by_stage('instinctive')
        store.update(memories[0]['id'], metadata={'title': 'Updated Ruby'})
        generator.write_manifest()

        second_content = (store.base_dir / 'MEMORY.md').read_text()
        assert 'Updated Ruby' in second_content
