"""
Manifest generator for memory lifecycle.

Generates a MEMORY.md index from SQLite metadata, preserving the
frontmatter-links + ~150-char summary format (D-02).
"""

import os
import shutil
import tempfile
from pathlib import Path

from core.storage import MemoryStore

# 200K token context window used for budget estimation
_CONTEXT_WINDOW = 200_000

# Stages listed in MEMORY.md (ephemeral is scratch; excluded)
_MANIFEST_STAGES = ['instinctive', 'crystallized', 'consolidated']

_STAGE_HEADERS = {
    'instinctive': 'Instinctive (always loaded)',
    'crystallized': 'Crystallized (context-matched)',
    'consolidated': 'Consolidated (available via search)',
}


def _truncate(text: str, max_len: int = 150) -> str:
    """Truncate a string to at most max_len characters."""
    if not text:
        return ''
    text = text.strip()
    if len(text) <= max_len:
        return text
    return text[:max_len - 1].rstrip() + '\u2026'


def _format_entry(memory: dict, base_dir: Path, include_importance: bool = False) -> str:
    """
    Format a single memory as a MEMORY.md list item.

    Pattern: `- [title](relative_path) — summary [importance: X.XX]`
    """
    title = memory.get('title') or Path(memory['file_path']).stem.replace('_', ' ').title()
    rel_path = os.path.relpath(memory['file_path'], base_dir)
    summary = _truncate(memory.get('summary') or '', 150)

    line = f'- [{title}]({rel_path})'
    if summary:
        line += f' \u2014 {summary}'

    if include_importance:
        importance = memory.get('importance', 0.5)
        line += f' [importance: {importance:.2f}]'

    return line


class ManifestGenerator:
    """
    Generates a MEMORY.md index from SQLite metadata.

    Reads stage lists from MemoryStore and produces a markdown document
    following the established frontmatter-links + summary format (D-02).
    """

    def __init__(self, store: MemoryStore):
        self._store = store

    def generate(self, project_context: str = None) -> str:
        """
        Generate MEMORY.md content as a string.

        Stages are rendered in this order: instinctive, crystallized,
        consolidated.  Ephemeral memories are excluded.  Empty stages
        produce no section header.

        Args:
            project_context: Ignored at generation time (reserved for future
                             per-project filtering).

        Returns:
            Complete MEMORY.md content.
        """
        instinctive = self._store.list_by_stage('instinctive')
        crystallized = sorted(
            self._store.list_by_stage('crystallized'),
            key=lambda m: m.get('importance', 0.5),
            reverse=True,
        )
        consolidated = sorted(
            self._store.list_by_stage('consolidated'),
            key=lambda m: m.get('updated_at') or '',
            reverse=True,
        )

        total = len(instinctive) + len(crystallized) + len(consolidated)
        token_count, token_pct = self.estimate_token_budget()

        lines = [
            '# Memory',
            '',
            '<!-- Auto-generated by memesis plugin -->',
            f'<!-- Total: {total} | Token budget: {token_pct * 100:.1f}% -->',
        ]

        base_dir = self._store.base_dir

        # Instinctive
        if instinctive:
            lines += [
                '',
                f'## {_STAGE_HEADERS["instinctive"]}',
                '',
            ]
            for memory in instinctive:
                lines.append(_format_entry(memory, base_dir))

        # Crystallized
        if crystallized:
            lines += [
                '',
                f'## {_STAGE_HEADERS["crystallized"]}',
                '',
            ]
            for memory in crystallized:
                lines.append(_format_entry(memory, base_dir, include_importance=True))

        # Consolidated
        if consolidated:
            lines += [
                '',
                f'## {_STAGE_HEADERS["consolidated"]}',
                '',
            ]
            for memory in consolidated:
                lines.append(_format_entry(memory, base_dir))

        lines.append('')
        return '\n'.join(lines)

    def estimate_token_budget(self) -> tuple[int, float]:
        """
        Estimate the token budget consumed by always-loaded memories.

        Counts characters in all instinctive file contents plus the top-10
        crystallized files (by importance), then divides by 4 for a rough
        token estimate.

        Returns:
            (token_count, fraction_of_200k_window)
        """
        char_count = 0

        # All instinctive
        for memory in self._store.list_by_stage('instinctive'):
            fp = Path(memory['file_path'])
            if fp.exists():
                char_count += len(fp.read_text(encoding='utf-8'))

        # Top-10 crystallized by importance
        crystallized = sorted(
            self._store.list_by_stage('crystallized'),
            key=lambda m: m.get('importance', 0.5),
            reverse=True,
        )
        for memory in crystallized[:10]:
            fp = Path(memory['file_path'])
            if fp.exists():
                char_count += len(fp.read_text(encoding='utf-8'))

        token_count = char_count // 4
        return token_count, token_count / _CONTEXT_WINDOW

    def write_manifest(self, project_context: str = None) -> None:
        """
        Write the generated MEMORY.md to {store.base_dir}/MEMORY.md.

        Args:
            project_context: Passed through to generate().
        """
        content = self.generate(project_context=project_context)
        manifest_path = self._store.base_dir / 'MEMORY.md'
        tmp_fd, tmp_path = tempfile.mkstemp(dir=manifest_path.parent, suffix='.tmp')
        try:
            os.write(tmp_fd, content.encode('utf-8'))
            os.close(tmp_fd)
            shutil.move(tmp_path, manifest_path)
        except Exception:
            try:
                os.close(tmp_fd)
            except OSError:
                pass
            if os.path.exists(tmp_path):
                os.unlink(tmp_path)
            raise
